AllCops:
  Include:
    - '**/*.glug'

Style/FrozenStringLiteralComment:
    Enabled: false

Layout/ArgumentAlignment:
    Enabled: true
    EnforcedStyle: with_fixed_indentation

Style/NilComparison:
    Enabled: true
    EnforcedStyle: comparison

Style/BlockDelimiters:
    Enabled: true
    EnforcedStyle: always_braces

Metrics/BlockLength:
    Enabled: true
    AllowedMethods: ['layer', 'on']

Layout/SpaceBeforeFirstArg:
    Enabled: True
    AllowedMethods: ['_!']

Layout/ArgumentAlignment:
    Enabled: True
    EnforcedStyle: with_fixed_indentation
